# Generated by Django 4.2.5 on 2023-09-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=255)),
                ('column2', models.CharField(max_length=255)),
                ('column3', models.CharField(max_length=255)),
                ('column4', models.CharField(max_length=255)),
                ('column5', models.CharField(max_length=255)),
            ],
        ),
    ]
